### ISSUE TITLE
proot info: vpid 1: terminated with signal 11

### ISSUE THREAD

**Issue by Jokerha419** [jorexdeveloper/termux-ubuntu#1]
![Screenshot_2024-04-16-17-47-51_com termux_1713289768478](https://github.com/jorexdeveloper/termux-ubuntu/assets/132017336/4b8a4c6a-d24c-48fe-b854-143da50e3d04)
After installing Ubuntu in termux it gives me this error. I tried uninstalling and installing but still this error keeps appearing.

**Comment by jorexdeveloper** [comment]
try re-installing using updated script.
